# Generated by Django 5.2.7 on 2025-10-20 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
