# Generated by Django 5.2.7 on 2025-10-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mecatos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='post',
            name='saludable',
            field=models.BooleanField(default=False),
        ),
    ]
