# Generated by Django 5.2.7 on 2025-10-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_disponible_post_imagen_post_precio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='disponible',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='saludable',
            new_name='is_healthy',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='precio',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
