# Generated by Django 5.2.7 on 2025-10-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_infocontacto_delete_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocontacto',
            name='correo',
        ),
    ]
